# Generated by Django 4.1.7 on 2023-03-27 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=datetime.datetime(2023, 3, 27, 5, 9, 1, 2373, tzinfo=datetime.timezone.utc), upload_to='gallery'),
            preserve_default=False,
        ),
    ]
